### PR TITLE
chore: upgrade @acid-info/lsd-react

### PR DESCRIPTION
**Pull request by jeangovil**

### CODE REVIEW

**Comment by nireims** [comment]
brand guidelines:

image

image

image

image

**Comment by amirhouieh** [comment]
Test comment

**Comment by nireims** [comment]
landing:

image

image

image

image

image

image

image

**Comment by amirhouieh** [comment]
@jeangovil in FAQ page, let's not use any transition effect as we do not use it anywhere else when LSD is used.

**Comment by nireims** [comment]
image

image

image

image

image

mobile:

image

image

**Pull request merged**
